version: '3.8'
services:
  pe-api:
    build:
      context: product_engine
      dockerfile: Dockerfile
    volumes:
      - ./database:/product_engine/database
    networks:
      - fintech-network
    ports:
      - "30:30"
    restart: unless-stopped
  origination-api:
    build:
      context: origination
      dockerfile: Dockerfile
    volumes:
      - ./database:/origination/database
    networks:
      - fintech-network
    ports:
      - "40:40"
    restart: unless-stopped
networks:
  fintech-network:
    external: true