version: '3.8'
services:
  pe-api:
    build:
      context: product_engine
      dockerfile: Dockerfile
    volumes:
      - ./database:/product_engine/database
      - ./utils:/product_engine/utils
    networks:
      - fintech-network
    ports:
      - "30:30"
    restart: unless-stopped
  origination-api:
    build:
      context: origination
      dockerfile: Dockerfile
    volumes:
      - ./database:/origination/database
      - ./utils:/origination/utils
    networks:
      - fintech-network
    ports:
      - "40:40"
    restart: unless-stopped
  scoring-api:
    build:
      context: scoring
      dockerfile: Dockerfile
    volumes:
      - ./database:/scoring/database
      - ./utils:/scoring/utils
    networks:
      - fintech-network
    ports:
      - "50:50"
    restart: unless-stopped
  gateway-api:
    build:
      context: gateway
      dockerfile: Dockerfile
    volumes:
      - ./database:/gateway/database
      - ./utils:/gateway/utils
    networks:
      - fintech-network
    ports:
      - "60:60"
    restart: unless-stopped
networks:
  fintech-network:
    external: true